//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.05 at 10:09:18 AM GMT 
//


package fish.payara.examples.jdays2016.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ha_planned_works" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="reference_number" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="road" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="local_authority" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="start_date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *                   &lt;element name="end_date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *                   &lt;element name="expected_delay" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="traffic_management" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="closure_type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="centre_easting" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="centre_northing" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="published_date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "haPlannedWorks"
})
@XmlRootElement(name = "ha_planned_roadworks")
public class HaPlannedRoadworks {

    @XmlElement(name = "ha_planned_works", required = true)
    protected List<HaPlannedRoadworks.HaPlannedWorks> haPlannedWorks;

    /**
     * Gets the value of the haPlannedWorks property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the haPlannedWorks property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHaPlannedWorks().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HaPlannedRoadworks.HaPlannedWorks }
     * 
     * 
     */
    public List<HaPlannedRoadworks.HaPlannedWorks> getHaPlannedWorks() {
        if (haPlannedWorks == null) {
            haPlannedWorks = new ArrayList<HaPlannedRoadworks.HaPlannedWorks>();
        }
        return this.haPlannedWorks;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="reference_number" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="road" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="local_authority" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="start_date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
     *         &lt;element name="end_date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
     *         &lt;element name="expected_delay" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="traffic_management" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="closure_type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="centre_easting" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="centre_northing" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="published_date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "referenceNumber",
        "road",
        "localAuthority",
        "location",
        "startDate",
        "endDate",
        "expectedDelay",
        "description",
        "trafficManagement",
        "closureType",
        "centreEasting",
        "centreNorthing",
        "status",
        "publishedDate"
    })
    public static class HaPlannedWorks {

        @XmlElement(name = "reference_number")
        protected int referenceNumber;
        @XmlElement(required = true)
        protected String road;
        @XmlElement(name = "local_authority", required = true)
        protected String localAuthority;
        @XmlElement(required = true)
        protected String location;
        @XmlElement(name = "start_date", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar startDate;
        @XmlElement(name = "end_date", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar endDate;
        @XmlElement(name = "expected_delay", required = true)
        protected String expectedDelay;
        @XmlElement(required = true)
        protected String description;
        @XmlElement(name = "traffic_management", required = true)
        protected String trafficManagement;
        @XmlElement(name = "closure_type", required = true)
        protected String closureType;
        @XmlElement(name = "centre_easting")
        protected int centreEasting;
        @XmlElement(name = "centre_northing")
        protected int centreNorthing;
        @XmlElement(required = true)
        protected String status;
        @XmlElement(name = "published_date", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar publishedDate;

        /**
         * Gets the value of the referenceNumber property.
         * 
         */
        public int getReferenceNumber() {
            return referenceNumber;
        }

        /**
         * Sets the value of the referenceNumber property.
         * 
         */
        public void setReferenceNumber(int value) {
            this.referenceNumber = value;
        }

        /**
         * Gets the value of the road property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRoad() {
            return road;
        }

        /**
         * Sets the value of the road property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRoad(String value) {
            this.road = value;
        }

        /**
         * Gets the value of the localAuthority property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLocalAuthority() {
            return localAuthority;
        }

        /**
         * Sets the value of the localAuthority property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLocalAuthority(String value) {
            this.localAuthority = value;
        }

        /**
         * Gets the value of the location property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLocation() {
            return location;
        }

        /**
         * Sets the value of the location property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLocation(String value) {
            this.location = value;
        }

        /**
         * Gets the value of the startDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getStartDate() {
            return startDate;
        }

        /**
         * Sets the value of the startDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setStartDate(XMLGregorianCalendar value) {
            this.startDate = value;
        }

        /**
         * Gets the value of the endDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getEndDate() {
            return endDate;
        }

        /**
         * Sets the value of the endDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setEndDate(XMLGregorianCalendar value) {
            this.endDate = value;
        }

        /**
         * Gets the value of the expectedDelay property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExpectedDelay() {
            return expectedDelay;
        }

        /**
         * Sets the value of the expectedDelay property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExpectedDelay(String value) {
            this.expectedDelay = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the trafficManagement property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTrafficManagement() {
            return trafficManagement;
        }

        /**
         * Sets the value of the trafficManagement property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTrafficManagement(String value) {
            this.trafficManagement = value;
        }

        /**
         * Gets the value of the closureType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClosureType() {
            return closureType;
        }

        /**
         * Sets the value of the closureType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClosureType(String value) {
            this.closureType = value;
        }

        /**
         * Gets the value of the centreEasting property.
         * 
         */
        public int getCentreEasting() {
            return centreEasting;
        }

        /**
         * Sets the value of the centreEasting property.
         * 
         */
        public void setCentreEasting(int value) {
            this.centreEasting = value;
        }

        /**
         * Gets the value of the centreNorthing property.
         * 
         */
        public int getCentreNorthing() {
            return centreNorthing;
        }

        /**
         * Sets the value of the centreNorthing property.
         * 
         */
        public void setCentreNorthing(int value) {
            this.centreNorthing = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatus(String value) {
            this.status = value;
        }

        /**
         * Gets the value of the publishedDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getPublishedDate() {
            return publishedDate;
        }

        /**
         * Sets the value of the publishedDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setPublishedDate(XMLGregorianCalendar value) {
            this.publishedDate = value;
        }

    }

}
